# Generated by Django 2.2.12 on 2020-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
