# Generated by Django 2.2.12 on 2020-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='emp_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
