# Generated by Django 2.2.12 on 2020-05-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200517_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='emp_image',
        ),
    ]
